# Generated by Django 4.2.2 on 2023-06-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('Resturant', 'Resturant'), ('Shopping', 'Shopping'), ('Hotel and Travel', 'Hotels And Travels'), ('Entertainment', 'Entertainment'), ('Health and Medical', 'Health And Medical'), ('Beauty and Spas', 'Beauty And Spas'), ('Automotive', 'Automotive'), ('Home and Garden', 'Home And Garden'), ('Pets', 'Pets'), ('Professionals', 'Professionals'), ('Education', 'Education'), ('Sport and Fitness', 'Sports And Fitness'), ('Others', 'Others')], default='Resturant', max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('review_text', models.TextField(max_length=1000)),
                ('date_of_vist', models.DateTimeField(auto_now_add=True)),
                ('main_photo', models.ImageField(blank=True, upload_to='posts/')),
                ('photo_1', models.ImageField(blank=True, upload_to='posts/')),
                ('photo_2', models.ImageField(blank=True, upload_to='posts/')),
                ('photo_3', models.ImageField(blank=True, upload_to='posts/')),
            ],
        ),
    ]
